import './globals.css';

export const metadata = {
  title: 'Kolkata Satta',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-zinc-100'>
        {children}
      </body>
    </html>
  );
}